# Build Stage
FROM --platform=linux/amd64 ubuntu:20.04 as builder
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y make gcc nasm

COPY . /SmallerC
WORKDIR /SmallerC
RUN ./configure
RUN make 

FROM ubuntu:20.04 as package
COPY --from=builder /SmallerC/smlrc /
